/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package finalproject;

/**
 *
 * @author Minhaz
 */
import java.awt.*;
import javax.swing.*;

public class forum extends javax.swing.JFrame {

    /**
     * Creates new form forum
     */
    public forum() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        ammoYes = new javax.swing.JCheckBox();
        gunType = new javax.swing.JComboBox<>();
        ammoNo = new javax.swing.JCheckBox();
        supYes = new javax.swing.JRadioButton();
        supNo = new javax.swing.JRadioButton();
        scope = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        quantity = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        enter = new javax.swing.JButton();
        delete = new javax.swing.JButton();
        mag = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        jList3 = new javax.swing.JList<>();
        gunName = new javax.swing.JComboBox<>();
        save = new javax.swing.JButton();
        exit = new javax.swing.JButton();
        background2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Information");
        setAlwaysOnTop(true);
        setPreferredSize(new java.awt.Dimension(800, 500));
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Type of Gun:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 30, 90, 20);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Gun name:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(20, 70, 80, 17);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Ammo:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(40, 150, 80, 20);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Scope:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(50, 220, 70, 30);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Suppressor:");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(20, 270, 80, 17);

        ammoYes.setText("yes");
        ammoYes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ammoYesActionPerformed(evt);
            }
        });
        getContentPane().add(ammoYes);
        ammoYes.setBounds(110, 150, 60, 23);

        gunType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "<none>", "Pistol", "Assult Rifel", "Sniper", "Smg", "Shotgun" }));
        gunType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gunTypeActionPerformed(evt);
            }
        });
        getContentPane().add(gunType);
        gunType.setBounds(110, 30, 150, 20);

        ammoNo.setText("no");
        ammoNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ammoNoActionPerformed(evt);
            }
        });
        getContentPane().add(ammoNo);
        ammoNo.setBounds(207, 150, 50, 23);

        supYes.setText("yes");
        supYes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                supYesActionPerformed(evt);
            }
        });
        getContentPane().add(supYes);
        supYes.setBounds(110, 270, 60, 23);

        supNo.setText("no");
        supNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                supNoActionPerformed(evt);
            }
        });
        getContentPane().add(supNo);
        supNo.setBounds(207, 270, 50, 23);
        getContentPane().add(scope);
        scope.setBounds(110, 230, 150, 20);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Quantity:");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(30, 110, 58, 17);

        jList1.setBackground(new java.awt.Color(204, 204, 204));
        jList1.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(0, 0, 204)));
        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "PRICES:-", "Magazine per round= $10", "Suppressor=$20", " ", "Scopes-", "2x=$20", "3x=$30", "4x=$40", "6x=$60", "8x=$80", " " };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(620, 0, 160, 220);

        quantity.setToolTipText("");
        getContentPane().add(quantity);
        quantity.setBounds(110, 110, 150, 20);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Magazine:");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(30, 190, 60, 17);

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Round's");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(270, 190, 70, 17);

        enter.setText("Enter");
        enter.setToolTipText("");
        enter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enterActionPerformed(evt);
            }
        });
        getContentPane().add(enter);
        enter.setBounds(50, 350, 80, 30);

        delete.setText("Delete");
        delete.setToolTipText("Clear all field");
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });
        getContentPane().add(delete);
        delete.setBounds(170, 350, 70, 30);

        mag.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                magActionPerformed(evt);
            }
        });
        getContentPane().add(mag);
        mag.setBounds(110, 190, 150, 20);

        jList3.setBackground(new java.awt.Color(153, 153, 153));
        jList3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 0, 51), 3, true));
        jList3.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jList3.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Gun Available", "(With price):-", "P92=$40", "P1911=$50", " ", "Ak-47=$120", "Scar-L=$140", "M416=$150", " ", "SLR=$300", "AWM=$500", "SKS=$250", " ", "UZI=$80", "Vector=$90", "UMP9=$100", " ", "S686=$180", "S12k=$190" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane3.setViewportView(jList3);

        getContentPane().add(jScrollPane3);
        jScrollPane3.setBounds(510, 0, 90, 330);

        gunName.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "<none>", "P92", "P1911", "Ak-47", "Scar-L", "M416", "SLR", "AWM", "SKS", "UZI", "Vector", "UMP9", "S686", "S12k" }));
        getContentPane().add(gunName);
        gunName.setBounds(110, 70, 150, 20);

        save.setText("Save in File");
        save.setToolTipText("");
        save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveActionPerformed(evt);
            }
        });
        getContentPane().add(save);
        save.setBounds(280, 350, 110, 30);

        exit.setBackground(new java.awt.Color(0, 0, 0));
        exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/finalproject/icons8-delete-64.png"))); // NOI18N
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });
        getContentPane().add(exit);
        exit.setBounds(350, 410, 70, 60);

        background2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/finalproject/red abstract.jpg"))); // NOI18N
        getContentPane().add(background2);
        background2.setBounds(0, 0, 800, 500);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ammoYesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ammoYesActionPerformed
        // TODO add your handling code here:
        if(ammoYes.isSelected()){
            ammoNo.setSelected(false);
        }
    }//GEN-LAST:event_ammoYesActionPerformed

    private void gunTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gunTypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_gunTypeActionPerformed

    private void supNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_supNoActionPerformed
        // TODO add your handling code here:
        if(supNo.isSelected()){
             supYes.setSelected(false);
        }
          
    }//GEN-LAST:event_supNoActionPerformed

    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed
        // TODO add your handling code here:
       
        gunType.setSelectedIndex(0);
        gunName.setSelectedIndex(0);
        quantity.setText(" ");
        mag.setText(" ");
        scope.setText(" ");
        ammoYes.setSelected(false);
        ammoNo.setSelected(false);
        supYes.setSelected(false);
        supNo.setSelected(false);
        
        
    }//GEN-LAST:event_deleteActionPerformed

    private void ammoNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ammoNoActionPerformed
        // TODO add your handling code here:
        if(ammoNo.isSelected()){
            ammoYes.setSelected(false);
        }
        mag.setText("0");
    }//GEN-LAST:event_ammoNoActionPerformed

    private void supYesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_supYesActionPerformed
        // TODO add your handling code here:
        if(supYes.isSelected()){
             supNo.setSelected(false);
        }
     
    }//GEN-LAST:event_supYesActionPerformed

    private void magActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_magActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_magActionPerformed

    private void enterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enterActionPerformed
        // TODO add your handling code here:
       
        String gunTypeV=(String)gunType.getSelectedItem();
        String gnV=(String)gunName.getSelectedItem();
        String quantityV=quantity.getText().trim();
        int quantityInt=Integer.parseInt(quantityV);
        String magV=mag.getText().trim();
        int magInt=Integer.parseInt(magV);
        String scopeV=scope.getText().trim();
        boolean ammoV=false,supV=false;
        if(ammoYes.isSelected()){
            ammoV=true;
        }
        if(ammoNo.isSelected()){
            ammoV=false;
        }
        if(supYes.isSelected()){
            supV=true;
        }
        if(supNo.isSelected()){
            supV=false;
        }
        
        Gun g1=new Gun(gunTypeV,gnV,quantityInt,ammoV,magInt,scopeV,supV);
        g1.priceHandle();
    }//GEN-LAST:event_enterActionPerformed

    private void saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveActionPerformed
        // TODO add your handling code here:
        String gunTypeV=(String)gunType.getSelectedItem();
        String gnV=(String)gunName.getSelectedItem();
        String quantityV=quantity.getText().trim();
        int quantityInt=Integer.parseInt(quantityV);
        String magV=mag.getText().trim();
        int magInt=Integer.parseInt(magV);
        String scopeV=scope.getText().trim();
        boolean ammoV=false,supV=false;
        if(ammoYes.isSelected()){
            ammoV=true;
        }
        if(ammoNo.isSelected()){
            ammoV=false;
        }
        if(supYes.isSelected()){
            supV=true;
        }
        if(supNo.isSelected()){
            supV=false;
        }
        
        Gun g2=new Gun(gunTypeV,gnV,quantityInt,ammoV,magInt,scopeV,supV);
        try{
        g2.writeFile();
        }catch(Exception e){
            System.out.println(" ");
        }
        JOptionPane.showMessageDialog(null,"Successfully written in File","Confirmation", 2);
    }//GEN-LAST:event_saveActionPerformed

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_exitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(forum.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(forum.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(forum.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(forum.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new forum().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox ammoNo;
    private javax.swing.JCheckBox ammoYes;
    private javax.swing.JLabel background2;
    private javax.swing.JButton delete;
    private javax.swing.JButton enter;
    private javax.swing.JButton exit;
    private javax.swing.JComboBox<String> gunName;
    private javax.swing.JComboBox<String> gunType;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JList<String> jList1;
    private javax.swing.JList<String> jList3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField mag;
    private javax.swing.JTextField quantity;
    private javax.swing.JButton save;
    private javax.swing.JTextField scope;
    private javax.swing.JRadioButton supNo;
    private javax.swing.JRadioButton supYes;
    // End of variables declaration//GEN-END:variables
}
